# Nixpacks Configuration for LivPulse v2.0 Backend
# This tells Railway exactly how to build and run our Node.js backend

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cd backend && npm ci --production=false"]

[phases.build]
cmds = ["cd backend && npm run build"]

[phases.start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
PORT = "10000"