# Railway Monorepo Configuration
# This file tells Railway to build the backend service

[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && npm run build"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "10000"

[build.env]
NODE_VERSION = "18"
NPM_VERSION = "9"

# Experimental features
[experimental]
nixpacksVersion = "1.15.0"