# Railway Configuration for LivPulse v2.0 Backend
# Uses Docker for reliable builds (avoiding Nixpacks issues)

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "10000"

# Health check configuration
[healthcheck]
path = "/api/health"
interval = 30
timeout = 10
retries = 3