[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
startCommand = "npm start"

[env]
NODE_ENV = "production"

# Required environment variables to set in Railway dashboard:
# DATABASE_URL = "postgresql://..." (auto-injected by Railway PostgreSQL)
# JWT_SECRET = "your-production-jwt-secret-256-bit"
# JWT_REFRESH_SECRET = "your-production-refresh-secret-256-bit"
# FRONTEND_URL = "https://liv-pulse-frontend.vercel.app"

[build.env]
NODE_VERSION = "18"
NPM_VERSION = "9"

# Resource configuration
[resources]
memory = "1GB"
cpu = "1"

# Health check configuration
[healthcheck]
path = "/api/health"
interval = 30
timeout = 10
retries = 3