# LivPulse v2.0 Dependency Management
# Automated dependency updates and security monitoring

name: Dependency Management

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  # Dependency Audit
  dependency-audit:
    name: Security Audit
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [backend, frontend]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ${{ matrix.component }}/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ./${{ matrix.component }}

    - name: Run security audit
      run: npm audit --audit-level moderate
      working-directory: ./${{ matrix.component }}

    - name: Check for vulnerabilities
      run: npm audit --json | jq '.vulnerabilities | length'
      working-directory: ./${{ matrix.component }}

  # Update Dependencies
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    needs: dependency-audit

    strategy:
      matrix:
        component: [backend, frontend]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ${{ matrix.component }}/package-lock.json

    - name: Update dependencies
      run: |
        npm update
        npm audit fix --force
      working-directory: ./${{ matrix.component }}

    - name: Run tests after update
      run: |
        npm ci
        npm run test:ci || true
      working-directory: ./${{ matrix.component }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore(${{ matrix.component }}): update dependencies'
        title: 'chore(${{ matrix.component }}): automated dependency updates'
        body: |
          ## Automated Dependency Updates

          This PR contains automated dependency updates for the ${{ matrix.component }}.

          ### Changes
          - Updated npm dependencies to latest versions
          - Fixed security vulnerabilities with `npm audit fix`

          ### Testing
          - [x] Dependencies installed successfully
          - [x] Basic tests pass (if available)

          Please review the changes and run full test suite before merging.
        branch: dependency-updates-${{ matrix.component }}
        delete-branch: true

  # License Compliance Check
  license-check:
    name: License Compliance
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [backend, frontend]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ${{ matrix.component }}/package-lock.json

    - name: Install license checker
      run: npm install -g license-checker

    - name: Check licenses
      run: |
        cd ${{ matrix.component }}
        npm ci
        license-checker --onlyAllow 'MIT;BSD;Apache-2.0;ISC;0BSD;BSD-2-Clause;BSD-3-Clause;Apache-1.1;Apache-1.0'
      continue-on-error: true

    - name: Generate license report
      run: |
        cd ${{ matrix.component }}
        license-checker --csv > ../licenses-${{ matrix.component }}.csv

    - name: Upload license report
      uses: actions/upload-artifact@v4
      with:
        name: license-report-${{ matrix.component }}
        path: licenses-${{ matrix.component }}.csv
        retention-days: 30